# Generated by Django 2.1.5 on 2020-10-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
