# Generated by Django 2.1.5 on 2020-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201027_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
